.github/CODEOWNERS
=> docs: CODEOWNER 추가

.github/workflows/develop_build_deploy.yml, Dockerfile, docker-compose.yml
- close #4
- gradle build + docker build 후 dockerhub로 푸시하고, ec2 서버에서 이를 pull 받아서 실행하는 워크플로입니다.
- 디스코드 '백엔드-업데이트' 채널로 gradle build scan 결과를 전송합니다.
- 
-
=> chore: CI/CD 워크플로우 작성

build.gradle, src/main/java/com/gdschongik/gdsc/global/config/QuerydslConfig.java, src/test/java/com/gdschongik/gdsc/config/TestQuerydslConfig.java
- close #17 
- build.gradle에 dependencies 추가
- QureydslConfig 추가
=> chore: Querydsl 세팅

src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
- close #49 
- dto 필드명 변경
- Member 클래스와 이름을 같게 통일했습니다.
-
=> fix: 전체 멤버 조회 request dto 수정

src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- close #62 
- dto의 필드들 모두 꺼내서 넘기도록 수정했습니다.
-
-
=> refactor: 멤버 도메인이 dto에 의존하지 않도록 개선

src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
=> feat: 온보딩 멤버 정보 조회 기능

src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
- close #84
- 온보딩 회원 정보 조회에 입금자명을 추가했습니다.
-
-
=> refactor: 온보딩 회원 정보 조회에 입금자명 추가

src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberPaymentRequest.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPaymentResponse.java
- close #79
- 회비 납부 처리 api를 구현했습니다.
- 기존 dto들이랑 틀이 같은 부분이 있어서 재활용을 해볼까했지만 문서화 작업에서 차이가 있어서 새로 만들어서 사용했습니다.
-
=> feat: 회비 납부 처리 api 구현

src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #113 
- 회원 목록 조회 api에 검색 기능을 추가했습니다.
-
-
=> feat: 회원 목록 조회 api에 검색 파라미터 추가

src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
- close #119
- 회원 정보 조회 API에 가입 상태를 추가했습니다.
- 승인 가능 여부를 판단하는 `isGrantAvailable` 메서드를 추가했습니다.
-
-
=> refactor: 회원 정보 조회 API에 가입 상태 추가

src/main/java/com/gdschongik/gdsc/domain/member/api/CommonMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/CommonMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberDepartmentResponse.java, src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
- close #124
- `CommonMemberService/Controller` 로 구현
- 재학생 인증 상태 체크 방식 변경
-
-
=> feat: 학과 목록을 반환하는 API 구현

src/main/java/com/gdschongik/gdsc/domain/discord/api/OnboardingDiscordController.java, src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java, src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- close #115
- 멤버정보 API에 bevy 가입상태 추가
- Bevy 연동하기 API 추가
- 가입조건 Requirement에 bevyStatus 추가
-
-
=> feat: GDSC Bevy 가입조건 관련 API 구현

src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
- close #131
- 학과가 null인 경우 발생하는 NPE를 처리했습니다.
-
-
=> fix: DTO의 학과 정보 로직 NPE 제거

src/main/java/com/gdschongik/gdsc/domain/member/api/CommonMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/CommonMemberService.java
- close #136 
- 학과 검색 API를 구현했습니다.
- 검색어가 null인 경우 기존 service 메서드를 이용해 모든 학과의 값을 반환하도록 했습니다.
-
-
=> feat: 학과 검색 API 추가

src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java, src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java, src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java, src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
- close #140
- 어드민 랜딩 상태 제거
- 랜딩상태를 파라미터로 전달
- 쿠키의 경우 프론트에서 오리진 맞춰주는 작업 필요
-
-
=> feat: 소셜 로그인 리다이렉트 시 랜딩 파라미터 추가

src/main/java/com/gdschongik/gdsc/global/discord/listener/PingpongListener.java
=> refactor: 디스코드 테스트 리스너를 개발서버에서만 활성화하도록 변경

src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberSignupRequest.java, src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
=> fix: 객체 타입에 대한 `@NotBlank` 및 `@Pattern` 삭제

.github/workflows/production_build_deploy.yml
=> chore: 프로덕션에서 도커 빌드 시 멀티 아키텍처 지원하도록 변경

.github/workflows/develop_build_deploy.yml, src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
=> fix: 레퍼러 없이 온보딩 페이지로 리다이렉트하도록 설정

src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java, src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
=> feat: 소셜 로그인 후 헤더로 엑세스 토큰 발급하는 임시 로직 추가

.github/workflows/production_build_deploy.yml
- close #160
- `docker compose up`를 `docker-compose up`으로 수정했습니다.
-
-
=> fix: 도커 컴포즈 실행 명령 수정

src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #164
- 승인 가능 회원 조회 API에 검색 기능을 추가했습니다.
-
-
=> feat: 승인 가능 회원 조회 API에 검색 기능 추가

src/main/resources/application-prod.yml
- close #166
- prod 환경 ddl-auto를 none으로 변경
-
-
=> chore: PROD 환경 JPA 설정 변경

src/main/java/com/gdschongik/gdsc/global/util/CookieUtil.java
- close #172 
- 배포 환경에서 쿠키의 SameSite 설정을 Lax로 변경
-
-
=> fix: 쿠키 SameSite 설정 변경

src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- close #175
- permitAll로 수정
-
-
=> fix: 메일 인증 API security 설정 수정

src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java, src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
=> hotfix: 쿼리 파라미터로 토큰 내려주도록 수정

src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java, src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
=> fix: 쿼리 파라미터로 토큰 내려주도록 수정

src/main/resources/application-prod.yml
- close #185
- ddl-auto를 update로 바꿨습니다. 다시 none으로 바꿀 예정입니다.
-
-
=> chore: 운영 서버에 DB 구조 재구축

src/main/resources/application-prod.yml
- close #188
- ddl-auto를 none으로 복구
-
-
=> chore: 운영 서버에 ddl-auto none으로 복구

.github/workflows/production_build_deploy.yml
- close #183
- flavor 설정을 해주지 않으면 자동으로 latest가 붙어버린다고 합니다. 해당 설정 false로 변경했습니다.
- image-tag value를 직접 주입했습니다.
- [flavor 설정](https://github.com/docker/metadata-action?tab=readme-ov-file#flavor-input)
-
=> chore: 이미지 태그가 자동 생성되는 것을 막고 직접 버전을 주입

src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java, src/main/java/com/gdschongik/gdsc/global/security/CustomUserService.java
=> fix: 소셜 로그인 후 마지막 로그인 시간을 업데이트하도록 수정

src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java, src/main/java/com/gdschongik/gdsc/global/common/constant/EmailConstant.java
=> feat: 재학생 인증메일 문구 수정 및 CSS 스타일링

src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java, src/test/java/com/gdschongik/gdsc/domain/email/HongikUnivEmailValidatorTest.java
=> hotfix: 이메일 정규식에 언더스코어를 허용하도록 수정

src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java, src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
=> fix: 리다이렉트 URL 세그먼트가 누락되어 있는 문제 수정

src/main/java/com/gdschongik/gdsc/domain/auth/application/JwtService.java, src/main/java/com/gdschongik/gdsc/domain/auth/domain/RefreshToken.java, src/main/java/com/gdschongik/gdsc/domain/discord/domain/DiscordVerificationCode.java
=> refactor: 엔티티 빌더에 대해 private 접근 제어자 추가

src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
=> feat: 2차 모집기간 이전 새로 가입한 멤버는 대기 페이지로 랜딩하도록 변경

src/main/java/com/gdschongik/gdsc/domain/auth/api/AuthController.java, src/main/java/com/gdschongik/gdsc/domain/auth/application/AuthService.java, src/main/java/com/gdschongik/gdsc/domain/auth/dto/request/LoginRequest.java, src/main/java/com/gdschongik/gdsc/domain/auth/dto/response/LoginResponse.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java, src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java, src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
=> feat: 어드민 전용 로그인 API 구현

src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
=> fix: 쿠키 수정 전까지 리다이렉트 URL을 온보딩으로 고정하도록 변경

src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
- close #238
- #223 이슈를 롤백했습니다.
-
-
=> refactor: baseUrl 결정 로직 롤백

.github/workflows/develop_build_deploy.yml, src/main/resources/application-security.yml
=> fix: 소셜 로그인 리다이렉트 URL 스키마를 HTTPS로 변경

build.gradle, src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java, src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java, src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java, src/main/java/com/gdschongik/gdsc/global/common/constant/WorkbookConstant.java, src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java, src/main/java/com/gdschongik/gdsc/global/util/WorkbookUtil.java
- close #236
- 멤버 정보 엑셀을 생성하기 위한 api를 구현했습니다.
-
-
=> feat: 멤버 정보 엑셀로 다운로드 API 추가

src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #242 
- 운영진이 선호하는 정렬 조건으로 수정했습니다.
-
-
=> refactor: 엑셀 정렬 조건 수정

.github/workflows/develop_build_deploy.yml, .github/workflows/develop_deploy.yml, .github/workflows/production_build_deploy.yml, .github/workflows/production_deploy.yml, .github/workflows/pull_request_gradle_build.yml, build.gradle
=> chore: Spotless가 YAML 파일을 체크하도록 설정 추가

.github/workflows/pull_request_gradle_build.yml
- close #126
- CI 워크플로우를 다른 워크플로우와 같이 `gradle/actions/setup-gradle@v3`를 사용하도록 수정했습니다.
- `actions/checkout`도 v4로 업그레이드 했습니다.
-
-
=> chore: CI 워크플로우 수정

src/main/java/com/gdschongik/gdsc/global/config/JavaMailSenderConfig.java, src/main/java/com/gdschongik/gdsc/global/config/PropertyConfig.java, src/main/java/com/gdschongik/gdsc/global/property/EmailProperty.java
=> refactor: 이메일 프로퍼티의 패키지 위치 변경

.github/workflows/pull_request_gradle_build.yml
=> fix: Gradle Build Scan Report를 발행하도록 CI 워크플로우 수정

.github/workflows/pull_request_gradle_build.yml
=> fix: CI 워크플로우에서 Gradle 빌드가 수행되는 문제 해결

src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
=> hotfix: spotless 적용

src/test/java/com/gdschongik/gdsc/repository/RepositoryTest.java
- close #270
- Repository 테스트 템플릿 구현
- Repository 테스트에 필요한 어노테이션들을 하나의 인터페이스에 담았습니다.
- 
-
=> test: 레포지토리 테스트 템플릿 구현

src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java, src/test/java/com/gdschongik/gdsc/integration/IntegrationTest.java
- close #290 
- 로그아웃 및 재로그인을 수행하는 테스트 유틸을 통합 테스트 템플릿에 추가해두었습니다.
- 테스트 작성 시 참고할 수 있는 조회 및 생성 테스트를 작성해두었습니다.
-
-
=> test: 온보딩 멤버 서비스 테스트 코드

src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
- close #269 
- ref #296
- 다시 열었습니다
-
-
=> test: 멤버 도메인 단위 테스트 

src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java, src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java, src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java, src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java, src/test/java/com/gdschongik/gdsc/global/common/constant/MemberConstant.java
- close #313
- 멤버 관련 클래스에서 활용하는 상수들을 MemberConstant 클래스로 추출하여 분리했습니다.
-
-
=> test: 멤버 테스트 상수들을 상수 클래스로 분리

src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java, src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java, src/main/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java, src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java, src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/PeriodTest.java, src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java, src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
- close #330 
-
- validation 테스트할때 startdate, endDate일부로 given에 변수 선언 해두었는데  적절한가?..싶어서 일단 의견 여쭈어봅니당
- VO만들 때 특히 불변성 구현할 때 생긴 궁금증입니당 불변성을 위한 final키워드를 매개변수에 써본 적이 없어서 정확히 Builder에 해야하는 건지에 대해 잘 모르겠습니다! 혹시 한 번 붙이면 다 붙여야 할지 아니면 Builder에만 붙이면 되는건지...여쭈어봅니당
VO를 쓰는 이유
- primitive타입의 기능들을 객체가 전부 사용하지 않을 때 사용
- 여러 곳에서 사용될 때 중복 코드 발생
- 여러곳에서 사용될 때 불변을 한번에 보장할 수 없다
이러한 세가지 이유 때문에 VO를 쓴다
이 세가지 제약조건을 만족해야 VO를 제대로 생성할 수 있
1. 불변성 (Immutable)
2. 동등성 (Equality)
3. 자가 유효성 검사 (Self-Validation)
=> feat: Recruitment의 VO Period 생성

src/main/java/com/gdschongik/gdsc/domain/member/application/listener/MemberAssociateEventListener.java
- close #372 
- 트랜잭션 분리되어있는걸 묶었습니다
-
-
=> refactor: 멤버 이벤트 트랜잭션 변경

src/main/java/com/gdschongik/gdsc/global/common/constant/WorkbookConstant.java, src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java
- close #384
- `MemberRole.REGULAR` 시트를 추가했습니다.
- 단순 시트 추가라서 테스트는 생략했습니다.
-
-
=> feat: 정회원 시트 추가

src/main/java/com/gdschongik/gdsc/global/util/formatter/PhoneFormatter.java
- close #402 
- PhoneFormatter가 null을 받은 경우 null을 그대로 반환하도록 수정했습니다.
-
-
=> fix: PhoneFormatter의 null 처리

src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java, src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- close #404
- ophiuchi 사용에 따라 생성되는 프록시 url `"https://local-onboarding.gdschongik.com"`을 cors 설정에 추가했습니다.
-
-
=> feat: 프록시 URL 추가

src/main/java/com/gdschongik/gdsc/domain/common/vo/Money.java, src/main/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCoupon.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java, src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java, src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java, src/main/java/com/gdschongik/gdsc/domain/membership/domain/RegularRequirement.java, src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java, src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java, src/main/java/com/gdschongik/gdsc/global/security/CustomOAuth2User.java
- close #382
- `this`를 필요한 경우에만 사용하도록 도메인 클래스들을 정리했습니다.
-
-
=> refactor: `this`를 필요한 경우에만 사용하도록 수정

src/main/java/com/gdschongik/gdsc/domain/coupon/api/OnboardingCouponController.java, src/main/java/com/gdschongik/gdsc/domain/coupon/application/CouponService.java, src/main/java/com/gdschongik/gdsc/domain/coupon/dao/IssuedCouponRepository.java, src/main/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCoupon.java
- close #407
- 사용가능한 내 발급쿠폰 조회하기 API를 구현했습니다.
- 현재 로그인한 멤버 기준으로 발급쿠폰을 조회합니다.
- 사용 가능한 것만 필터링합니다.
-
-
=> feat: 사용 가능한 내 발급쿠폰 조회하기 API 구현

src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java, src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
- close #417 
-세션도 동일하게 필드명 수정하였습니다 
-추가로 sessionDescription, sessionStartAt도 동일하게 변경하였어요~
-
-
=> refactor: 스터디 세션 엔티티 필드명 수정

src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java, src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java, src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyStatus.java, src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java, src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
- close #421
- StudyStatus추가 (NONE, OPEN, CANCELLED)
- Study테이블에 있던 총 주차수컬럼명 변경 (sessionCount -> totalWeek)
- StudyDetail테이블에 있던 현 주차수 컬럼명 변경 (currentCount -> week)
-
-
=> refactor: 스터디 세션 및 과제 상태 enum값 추가

src/main/java/com/gdschongik/gdsc/domain/order/domain/OrderValidator.java, src/main/java/com/gdschongik/gdsc/global/annotation/DomainFactory.java, src/main/java/com/gdschongik/gdsc/global/annotation/DomainService.java
=> feat: 도메인 서비스 및 도메인 팩토리 어노테이션 추가

src/main/java/com/gdschongik/gdsc/domain/member/dto/MemberDto.java
=> fix: 멤버 DTO  필드 추가

build.gradle
=> hotfix: ZonedDateTime 역직렬화 지원 의존성 추가

build.gradle, src/main/java/com/gdschongik/gdsc/infra/feign/global/config/FeignConfig.java
=> hotfix: JavaTimeModule 세팅

src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
- close #677
- difficulty를 제거하고 deadline과 description을 추가했습니다.
-
-
=> refactor: 과제 매핑 정보 수정

src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryCustomRepositoryImpl.java
- close #828
- https://github.com/GDSC-Hongik/gdsc-server/pull/825#discussion_r1891160971 에서 논의한 내용 반영했습니다.
- (long)으로 타입 캐스팅 하던걸 requireNonNull에 담아서 처리했습니다.
-
-
=> refactor: 불필요한 명시적 타입 캐스팅 제거

src/main/java/com/gdschongik/gdsc/domain/studyv2/domain/StudyAchievementV2.java
=> feat: 우수 스터디원 V2 도메인 구현

.github/workflows/pull_request_automation.yml
=> chore: PR 자동화 스크립트가 초기 테스트 실패 시 동작하지 않는 문제
