gdg-hongik-univ/gdsc-server

- settings.gradle
- close #6
- Gradle Build Scan 레포트를 발행하려면 약관 동의가 필요함
- `setting.gradle` 에 약관 동의하는 코드 추가
- CI 환경에서만 publish 되도록 설정
- 
-
> chore: Gradle build scan 레포트 발행 활성화

- .github/workflows/pull_request_gradle_build.yml
- #8 
- 테스트를 강제하기 위한 PR Code Build
-  Pull Request Open, Synchronize, Closed시 Gradle Build 하는 workflows 작성
- JDK는 CI/CD와 같이 17 버전 temurin 사용 예정 -> [참고글](https://whichjdk.com/ko/)
- Closed시엔 필요 없을 수도 있는데, 혹시 몰라서 넣었음.
> chore : Gradle Check 수행하는 CI Workflows 작성

- src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomOAuth2User.java
- src/main/java/com/gdschongik/gdsc/global/util/CookieUtil.java
- close #29 
- `CustomOAuth2User` 의 부모 생성자를 호출할 때 잘못된 인자를 전달하는 오류를 수정했습니다 (이름 -> 이름 속성의 키)
- 쿠키가 올바르게 설정되지 않는 문제를 해결했습니다.
-
-
> fix: JWT 필터 로직 수정

- src/main/java/com/gdschongik/gdsc/domain/auth/application/JwtService.java
- src/main/java/com/gdschongik/gdsc/domain/auth/dao/RefreshTokenRepository.java
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/java/com/gdschongik/gdsc/global/exception/CustomException.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorResponse.java
- src/main/java/com/gdschongik/gdsc/global/exception/GlobalExceptionHandler.java
- src/main/java/com/gdschongik/gdsc/global/security/JwtExceptionFilter.java
- src/main/java/com/gdschongik/gdsc/global/security/JwtFilter.java
- src/main/java/com/gdschongik/gdsc/global/util/JwtUtil.java
- close #16
- GlobalExceptionHandler로 CustomException, RuntimeException 처리
- ErrorResponse, ErrorCode 추가
- JwtFilter에서 발생하는 Exception을 처리할 JwtExceptionFilter 추가
> feat: exception handling

- src/main/java/com/gdschongik/gdsc/global/common/constant/EnvironmentConstant.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/java/com/gdschongik/gdsc/global/util/CookieUtil.java
- src/main/java/com/gdschongik/gdsc/global/util/EnviromentUtil.java
- src/main/java/com/gdschongik/gdsc/global/util/EnvironmentUtil.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-redis.yml
- src/main/resources/application-security.yml
- src/main/resources/application.yml
- close #18 
- `application.yml` 을 운영환경에 맞게 분리했습니다. (local, dev, ...)
- security, redis 설정을 분리했습니다.
- 현재 서비스의 운영환경을 확인할 수 있는 유틸리티를 구현했습니다.
- CORS 설정을 추가했습니다.
- 운영환경에 따라 허용 origin을 다르게 설정하도록 구현했습니다.
- 운영환경에 따라 쿠키의 SameSite 정책을 다르게 설정하도록 구현했습니다.
- 그 외 자잘하게 리팩토링 필요한 부분들을 개선했습니다.
-
-
> chore: 프로파일 분리 및 운영환경 유틸리티 관련 기능 추가

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberStatus.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomUserService.java
- close #25 
- 멤버 삭제
- redis에서 토큰 삭제
> feat: 멤버 탈퇴 api 구현

- build.gradle
- src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/SwaggerUrlConstant.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/PropertyConfig.java
- src/main/java/com/gdschongik/gdsc/global/config/SwaggerConfig.java
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/java/com/gdschongik/gdsc/global/property/SwaggerProperty.java
- src/main/java/com/gdschongik/gdsc/global/security/JwtFilter.java
- src/main/java/com/gdschongik/gdsc/global/util/CookieUtil.java
- src/main/java/com/gdschongik/gdsc/global/util/EnvironmentUtil.java
- src/main/resources/application-swagger.yml
- src/main/resources/application.yml
- close #21
- 스웨거 세팅을 진행했습니다.
- 스웨거 사용 시 개발서버에서 basic auth 적용되도록 `@ConditionalOnProperty` 사용하여 스웨거 전용 필터체인을 만들었습니다.
- 인증 스키마 추가하여 스웨거에서 엑세스 토큰 사용할 수 있게 작업해두었습니다.
-
-
> chore: Swagger 세팅

- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/util/MemberUtil.java
- close #19
- 현재 로그인한 멤버를 `SecurityContext` 로부터 읽어오는 유틸리티를 구현했습니다.
- 서비스 레이어에서 주입받아서 사용하면 됩니다.
- 멤버의 모든 필드가 필요하면 `getCurrentMember` 를 통해 엔티티로 조회해와서 사용하고, id 값만 필요한 경우 `getCurrentMemberId` 로 사용하면 됩니다.
-
-
> feat: 현재 로그인한 멤버 조회하는 유틸리티 구현

- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/requirement/domain/Requirement.java
- src/main/java/com/gdschongik/gdsc/domain/requirement/domain/RequirementStatus.java
- close #42
- requirement 구현
- member 생성 시 requirement도 같이 생성하도록 수정
-
-
> feat: requirement 도메인 구현

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberStatus.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorResponse.java
- src/main/java/com/gdschongik/gdsc/global/exception/GlobalExceptionHandler.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/MemberServiceTest.java
- close #24 
- 회원 정보 수정을 위한 api, service, dto 추가
- GlobalExceptionHandler에 값 검증 예외 처리를 위한 메서드 추가
-
-
> feat: 어드민 멤버 정보 수정 api 구현

- build.gradle
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/resources/application-actuator.yml
- src/main/resources/application.yml
- close #53
- 스프링부트 액추에이터를 추가했습니다.
- ELB에서 헬스체크 시 `/gdsc-actuactor/health` 로 요청을 보내도록 합니다.
- 액추에이터 관련 보안설정을 적용했습니다.
- 모든 엔드포인트를 기본적으로 비활성화 처리했습니다 (enabled-by-default)
- jmx 방식은 모든 endpoint를 사용하므로 비활성화 처리했습니다.
- health 관련 엔드포인트만 활성화하도록 추가했습니다.
- 액추에이터 디폴트 경로를 `/gdsc-actuator` 로 설정하여 uri 스캔 공격을 회피할 수 있도록 했습니다.
-
-
> feat:  헬스체크 API를 위한 actuator 설정

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
- close #45
- swagger 세팅 이전에 작업한 내용들에 설명 추가
- 이후 작업하는 api들은 해당 브랜치에서 swagger 작업도 같이 하겠습니다.
-
> docs: admin member api 문서화

- .github/workflows/develop_deploy.yml
- close #55 
- Actions 페이지의 `Deploy to develop` 탭에서 `commit_hash` 를 입력하여 수동으로 워크플로우를 실행합니다.
- `commit_hash` 의 경우 도커허브의 이미지 태그로 들어갑니다. 
-
-
> chore: 도커허브에 올라간 이미지를 재배포하는 워크플로우 추가

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/RequirementStatus.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
- close #22
- 대기중인 멤버 조회를 위한 dto, service, repository 구현
- requirement 파일들의 위치를 member 디렉토리 내부로 옮겼습니다
-
> feat: 어드민 대기중인 멤버 조회 api 구현 

- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- close #58
- 현재 dev 서버 스웨거 접속 시 github oauth2 로그인 창으로 리다이렉트되는 문제가 있습니다.
- 이는 권한없는 요청인 경우 스프링 시큐리티의 oauth2 설정이 `OAuth2AuthorizationRequestRedirectFilter` 에 의해 강제로 `oauth2/authorization/github` 로 리다이렉트 되도록 설정되어 있기 때문입니다. 
- 스웨거의 경우 basic auth를 사용하고 있기 때문에 `BasicAuthenticationEntryPoint` 가 작동해야 하지만, 이는 `ExceptionTranslationFilter` 에서 수행됩니다. 해당 필터는 OAuth 필터보다 뒤에 존재하기 때문에 oauth의 리다이렉트 요청이 먼저 처리되는 것입니다.
- 이러한 문제 때문에 #40 에서 별도의 `swaggerFilterChain` 을 타도록 해주었지만 이때 oauthLogin 옵션을 disable 처리해주지 않아 해당 문제가 발생했습니다.
- 아울러, 디폴트 요청이 타게 되는 `filterChain` 에서도 리다이렉트 문제가 발생하기 때문에 이를 해결해주어야 합니다. 인증 예외가 발생했을 때 대부분의 예외는 디폴트로 `LoginUrlAuthenticationEntryPoint` 에 의해서 처리됩니다. 실제로 해당 클래스의 `commence()` 에서 리다이렉트 로직을 확인할 수 있습니다.
- `HttpSecurity` 의 `exceptionHandling` 에서 `authenticationEntryPoint` 를 커스텀해주면 스프링 시큐리티는 이렇게 …
> fix: 스웨거 Basic Auth가 작동하지 않는 문제 해결

- src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomOAuth2User.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
- src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
- close #61
- 소셜 로그인 후 유저가 어디로 랜딩할지를 결정하는 헤더를 추가했습니다.
- 헤더 이름은 `Landing-Status` 입니다.
- 헤더는 `TO_STUDENT_AUTHENTICATION` / `TO_REGISTRATION` / `TO_DASHBOARD` 세 가지 상태를 가집니다.
- 각각 재학생 인증 페이지 / 가입신청 페이지 / 대시보드 페이지를 의미합니다.
- 결정 로직은 다음과 같습니다.
- `univStatus` 가 `PENDING` 이면 재학생 인증 페이지로 랜딩합니다.
- 가입신청을 하지 않았다면 학번이 null입니다. 따라서 학번이 null이면 가입신청 페이지로 랜딩합니다.   
- 그 외의 경우에는 대시보드 페이지로 랜딩합니다.
-
-
> feat: 소셜 로그인 시 랜딩할 페이지 결정에 사용할 헤더 추가

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberGrantRequest.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberGrantResponse.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/MemberServiceTest.java
- close #23
- 승인할 멤버들의 id(pk)를 리스트로 받아서 승인된 멤버들의 id만 모아서 리스트로 반환합니다.
- **_3가지 requirement_**(재학생, 회비, 디스코드)의 승인 여부는 쿼리에서 확인하도록 구현했습니다.
-
-
> feat: 어드민 멤버 가입신청 승인하기 api 구현

- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberSignupRequest.java
- close #67
- 기획 변경에 따라 request dto를 수정했습니다.
-
-
> refactor: 멤버 가입 신청 request dto 수정

- build.gradle
- src/main/java/com/gdschongik/gdsc/domain/discord/listener/PingpongListener.java
- src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
- src/main/java/com/gdschongik/gdsc/global/config/PropertyConfig.java
- src/main/java/com/gdschongik/gdsc/global/discord/Listener.java
- src/main/java/com/gdschongik/gdsc/global/discord/ListenerBeanPostProcessor.java
- src/main/java/com/gdschongik/gdsc/global/property/DiscordProperty.java
- src/main/resources/application-discord.yml
- src/main/resources/application.yml
- src/test/java/com/gdschongik/gdsc/GdscApplicationTests.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
- src/test/resources/application-test.yml
- close #27
- JDA 관련 세팅을 완료했습니다.
- 디스코드 봇은 기본적으로 리스너 기반으로 작동합니다.
- 해당 리스너를 컴포넌트로 추가합니다. 이때 빈 후처리기를 통해 `@Listener` 로 annotated 된 빈을 `jda.addEventListener` 을 통해 동적으로 리스너로 등록되도록 해주었습니다.
- 이렇게 하면 매번 리스너를 구현할 때마다 jda config에서 리스너를 추가할 필요가 없습니다.
- 테스트에 필요한 핑퐁 리스너를 추가해두었습니다. GDSC 개발채널 링크로 테스트 서버 접속하셔서 `!ping` 으로 테스트 가능합니다.
- 리스너 빈 후처리기(`ListnerBeanPostProcessor`)의 경우 JDA 외부 의존성을 주입받습니다. 따라서 `@Component` 가 아니라 `DiscordConfig` 에서 `@Bean` 으로 등록해주어야 합니다.
- 이떄 테스트 환경에서 디스코드 봇 토큰 값을 주입받을 수 없으므로 JDA 초기화에 실패합니다. 따라서 테스트 환경에서는 `discord.enabled: false` 를 설정하고 `@ConditionalOnProperty` 를 통해 로드하지 않도록 설정합니다.
- 한편 리스너 빈 후처리기의 경우 JDA가 존재하지 않은 경우 초기화되지 않아야 하므로 `@ConditionalOnBean` 으로 설정해두었습니다.
-
> chore: 디스코드 연동 세팅

- src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/OnboardingMemberUpdateRequest.java
- close #52
- 변경된 기획 내용에 따라 username, nickname 두 가지만 수정하도록 했습니다.
- endpoint에서 memberId를 제거했는데 이 부분에 대해 의견 부탁드립니다. 활용하지 않더라고 경로에 있는게 맞을지 모르겠습니다.
-
-
> feat: 온보딩 멤버 정보 수정하기

- src/main/java/com/gdschongik/gdsc/domain/discord/api/OnboardingDiscordController.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/OnboardingDiscordService.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dao/DiscordVerificationCodeRepository.java
- src/main/java/com/gdschongik/gdsc/domain/discord/domain/DiscordVerificationCode.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dto/response/DiscordVerificationCodeResponse.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dto/response/LinkDiscordResponse.java
- src/main/java/com/gdschongik/gdsc/domain/discord/listener/RegisterCommandListener.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/DiscordConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/property/DiscordProperty.java
- src/main/resources/application-discord.yml
- close #48
- 디스코드 인증코드 발급 기능을 구현했습니다.
- `/인증코드` 커맨드를 서버에 추가합니다. jda 구성 시 수행됩니다. 
- `/인증코드` 로 커맨드를 실행합니다. 
- 이때 비즈니스 로직 처리를 위해 `deferReply` 를 사용합니다.
- 해당 기능은 `인증코드를 발급받는 중입니다...` 와 같이 로딩 메세지를 출력하여 최종 응답을 지연시킵니다.
- `setEphemeral(true)` 를 통해 자신에게만 메세지가 보이도록 설정합니다.
- 4자리로 된 랜덤 코드를 발급합니다. 이때 보안을 위해 `SecureRandom` 으로 발급합니다. 
- 커맨드를 실행한 유저 정보로부터 디스코드 유저네임(핸들명)을 받아옵니다.
- 유저네임을 키로, 랜덤코드를 값으로 하여 레디스에 저장합니다. ttl은 5분으로 설정합니다.
- `getHook().sendMessage()`로 지연된 요청에 대하여 응답을 보냅니다.
- `setEphemeral(true)` 를 통해 자신에게만 메세지가 보이도록 설정합니다.
- 디스코드 전용 상수 클래스를 추가하여, 1) 커맨드 이름 2) 커맨드 설명 3) 디스코드 클라이언트에 출력될 메세지 등을 해당 클래스에서 관리하도록 했습니다.
- 디스코드 커맨드 전용 채널이 필요합니다.
- 커맨드 외 일반 메세지를 보낼 경우 자동으로 삭제 처리하는 기능이 필요합니다.
- 테스트 디스코드 서버와 실제 디스코드 서버 간 환경을 맞춰줘야 합니다. (특히 채널이름, 역할 정책 관련)
> feat: 디스코드 인증코드 발급하기 기능 구현

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
- close #81 
- 쿼리에 eqStatus를 추가했습니다.
- 대기중인 멤버 조회 기능의 repository 메서드는 querydsl로 변경했습니다.
-
-
> refactor: 탈퇴 회원을 조회 api에서 제외

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #80
- 최신 생성 순으로 정렬하도록 수정
-
- 현재 기획 상으로는 정렬 조건을 바꾸는 기능이 프론트에 없어서 정렬 조건을 Pageable로 받기보다 createdAt.desc으로 고정하도록 메서드를 수정했습니다. 향후 프론트에서 정렬 조건을 지정하는 기능을 추가하면 Pageable로 받아서 정렬을 처리해줘도 좋을 것 같습니다.
> refactor: 조회 api 정렬 조건 추가

- src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberUnivStatusResponse.java
- close #76
- 재학생 인증 여부를 확인하기 위한 api를 구현했습니다.
- 
-
-
> feat: 재학생 인증 여부 확인  api 구현

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- close #78
- 회비 미납 회원 조회 api를 구현했습니다.
- 기존에 RepositoryImpl에서 사용하던 `paymentVerified`메서드를 `eqPaymentStatus`로 수정하여 재활용 가능하도록 했습니다.
-
-
> feat: 회비 미납 회원 목록 조회 api 구현

- src/main/java/com/gdschongik/gdsc/global/annotation/ConditionalOnProfile.java
- src/main/java/com/gdschongik/gdsc/global/annotation/OnProfileCondition.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/EnvironmentConstant.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/SwaggerUrlConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/SwaggerConfig.java
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/java/com/gdschongik/gdsc/global/util/EnvironmentUtil.java
- close #94
- 문제 원인
- `@ConditionalOnProperty(name = "spring.profiles.active", havingValue = "dev") ` 에서 local인 경우에는 필터체인을 타지 않아 발생하는 문제. local인 경우에도 스웨거 필터체인 빈이 로드되도록 해야 함
- 프로파일에 따라 빈 등록 여부를 결정할 수 있는 `@ConditionalOnProfile` 구현
- `@ConditionalOnProfile({DEV, LOCAL})` 와 같이 dev, local 환경인 경우 로드되도록 함
- 인자로 `EnvironmentConstants` enum 상수 배열을 전달할 수 있음.
- 해당 상수가 가지고 있는 환경변수 리터럴 값과 / 현재 실행 환경변수 값이 일치하는 경우 애플리케이션 컨텍스트에 로드함
- `EnvironmentConstants` 를 enum 클래스로 리팩토링
- 단 기존 상수 리터럴도 사용할 수 있도록 inner static class로 정의함. 이때 초기화 막기 위해 private 기본 생성자 정의.
-
-
> fix: 로컬 스웨거가 작동하지 않는 문제 수정

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPaymentFindAllResponse.java
- close #96
- status 쿼리 파라미터를 이용해 회비 납부 정보를 납부 상태에 따라 분리해서 볼 수 있도록 변경했습니다.
-
-
> refactor: 회비 납부 정보를 전체, 미납, 납부로 나누어 볼 수 있도록 수정

- src/main/java/com/gdschongik/gdsc/domain/discord/api/OnboardingDiscordController.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/OnboardingDiscordService.java
- src/main/java/com/gdschongik/gdsc/domain/discord/domain/DiscordVerificationCode.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dto/request/DiscordLinkRequest.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dto/response/DiscordVerificationCodeResponse.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dto/response/LinkDiscordResponse.java
- src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/OnboardingMemberUpdateRequest.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- close #90
- 인증코드 4자리, 닉네임, 디스코드 유저네임을 받아서 디스코드 연동을 수행합니다. 인증번호가 일치하는 경우 닉네임과 디스코드 유저네임을 해당 멤버 정보에 업데이트해주고, 연동상태를 `VERIFIED` 로 변경합니다.
- 인증코드의 타입을 `Long` 에서 `Integer` 로 변경했습니다.
- `verifyPayment` 메서드를 `updatePaymentStatus` 로 이름을 변경했습니다.
-
-
> feat: 디스코드 연동하기 API 구현

- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
- close #103
- dto에서 발생 가능한 phone의 NPE를 제거했습니다.
-
-
> fix: dto의 phone에서 발생 가능한 NPE 제거

- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberGrantResponse.java
- src/main/java/com/gdschongik/gdsc/global/config/QuerydslConfig.java
- close #105
- 프론트의 요청에 따라 승인된 멤버와 승인되지 않은 멤버를 모두 응답에 담도록 수정했습니다.
- pk보다 직관적인 name을 담도록 수정했습니다.
-
-
> refactor: 회원 승인 응답에 이름을 담도록 수정

- .github/workflows/develop_build_deploy.yml
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #107
- querydsl의 transform에서는 해당하는 원소가 없으면 빈 리스트가 아니라 null을 반환하기 때문에 발생하는 NPE가 있음을 확인하고 수정했습니다.
-
-
> fix: 승인 과정에서 발생하는 npe 처리

- src/main/java/com/gdschongik/gdsc/domain/discord/application/OnboardingDiscordService.java
- src/main/java/com/gdschongik/gdsc/domain/discord/dto/response/DiscordNicknameResponse.java
- src/main/java/com/gdschongik/gdsc/domain/discord/handler/JoinCommandHandler.java
- close #118 
- 역할 할당 가능한지 체크하는 서비스 메서드가 디스코드 닉네임 응답 DTO를 변환하도록 변경했습니다.
-
-
> feat: 디스코드 가입하기 핸들러에 서버 닉네임 업데이트 로직 추가

- .github/workflows/develop_build_deploy.yml
- build.gradle
- src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
- src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
- close #123
- 프론트에서 요청 보낼 때 CORS 에러 발생하는 이슈 -> 프론트에서 직접 리다이렉트 하도록 이슈 추가
- 서버에서는 referer 헤더 기반으로 sendRedirect 하도록 수정 (`{baseUrl}/social-login/redirect`)
- `@EnableWebSecurity(debug = true)` 사용 시 발생하는 이슈로 인해 스프링부트 버전업
-
-
> feat: 소셜 로그인 후 리다이렉트 경로를 지정하도록 변경

- src/main/java/com/gdschongik/gdsc/domain/discord/application/CommonDiscordService.java
- src/main/java/com/gdschongik/gdsc/domain/discord/handler/NicknameModifyHandler.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/global/discord/exception/DiscordEventHandlerAspect.java
- src/main/java/com/gdschongik/gdsc/global/discord/exception/DiscordExceptionDispatcher.java
- src/main/java/com/gdschongik/gdsc/global/discord/exception/DiscordExceptionMessageGenerator.java
- src/main/java/com/gdschongik/gdsc/global/discord/exception/handler/CommandExceptionHandler.java
- src/main/java/com/gdschongik/gdsc/global/discord/exception/handler/DefaultExceptionHandler.java
- src/main/java/com/gdschongik/gdsc/global/discord/exception/handler/DiscordExceptionHandler.java
- src/main/java/com/gdschongik/gdsc/global/discord/listener/NicknameModifyListener.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- close #117 
- 서버 닉네임 변경 이벤트가 발생한 경우 트리거됩니다.
- 닉네임 변경 이벤트는 다음 상황에서 발생합니다.
- `/가입하기` 커맨드로 닉네임을 변경시키는 경우
- 본인이 직접 서버 프로필을 수정하는 경우
- 닉네임 변경 이벤트가 발생한 경우, 다음과 같이 작동합니다.
- 디비에 저장된 멤버인 경우
- 디비에 닉네임이 존재하는 경우
- 바꾸려는 닉네임이 현재 디비 닉네임인 경우 -> 패스
- 디비 닉네임과 바꾸려는 닉네임이 다른 경우 ->
- 디비에 닉네임이 존재하지 않는 경우 -> 패스
- 디비에 저장되지 않은 멤버인 경우
- 패스 
- 디스코드 예외 처리기 리팩토링
- 디스코드 AOP의 경우 try-catch around만 수행하고 실제 예외처리는 디스패쳐에서 예외 핸들러를 디스패치 한 후 핸들링을 수행하도록 변경 
-
-
> feat: 디스코드 서버 닉네임 변경 시 자동으로 원복하는 기능 구현

- src/main/java/com/gdschongik/gdsc/domain/discord/handler/NonCommandHandler.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/DiscordConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
- src/main/java/com/gdschongik/gdsc/global/discord/listener/NonCommandListener.java
- src/main/java/com/gdschongik/gdsc/global/property/DiscordProperty.java
- src/main/resources/application-discord.yml
- close #191 
- close #192
- 명령어 채널에서 운영진 or 봇 제외한 유저가 채팅 올리는 경우 자동으로 삭제
- 명령어 채널 ID `.env` 에 넣어야 함
- 운영진 역할 이름은 `운영진`
- 삭제하기 전에 잠깐 보이긴 함. 한번에 여러 명이 스패밍하면 큐잉 딜레이 생기는데 어쩔 수 없음 -> 수동으로 막아야 함
-
-
> feat: 디스코드 명령어 채널에서 잘못 입력한 커맨드 삭제하는 기능

- src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
- src/main/java/com/gdschongik/gdsc/global/util/email/VerificationLinkUtil.java
- close #207
- 기존 UrlConstant에 있던 `PROD_CLIENT_URL`, `PROD_CLIENT_URL`을 Onboarding을 넣어 rename 했습니다.
- 어드민 UrlConstant를 생성하고 cors 설정에 추가했습니다.
- 
-
> chore: 클라이언트 어드민 URL에 대한 CORS 설정

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Department.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
- close #201 
- 어드민에서 검색 조건을 학과로 설정하여 요청을 보낼 경우 유저는 학과 코드가 아닌 학과명을 입력하기 때문에 자료형을 String으로 수정했습니다.
- department로 "컴"만 들어온 경우 "컴"이 포함된 모든 코드를 사용해 쿼리가 나가도록 하기 위해 dto에 `List<Department>` 생성 메서드를 넣었습니다.
-
-
> refactor: 검색 조건에서 학과를 문자열로 받도록 수정

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #226
- 회비 납부 여부 조회 시 가입 신청서 작성한 회원만 포함하도록 수정했습니다.
-
-
> refactor: 회비 납부 여부 조회 시 가입 신청서 작성한 회원만 포함

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #230
- 대기중인 멤버 조회 api에서 가입 신청서를 작성하지 않은 멤버 제외했습니다. (학번의 유무로 판단)
- count query가 실제 쿼리와 같은 조건을 갖도록 수정했습니다.
-
-
> refactor: 대기중인 멤버 조회 API에서 가입 신청서를 작성하지 않은 멤버 제외

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- close #229 
- 승인된 멤버를 조회하는 api를 구현했습니다.
- service에서 repository로 넘어가는 부분에서 합칠 수 있는 메서드가 있어서 repository의 메서드를 정리했습니다. '전체 멤버 조회' 시 사용하던 `MemberCustomRepository.findAll`을 `MemberCustomRepository.findAllByRole`로 대체했고, `MemberCustomRepository.findAllByRole`의 parameter MemberRole을 `@Nullable`로 수정했습니다.
-
-
> feat: 승인된 멤버 조회 API 추가

- .github/workflows/develop_deploy.yml
- .github/workflows/production_deploy.yml
- close #244
- 개발서버 수동배포 -> 도커허브 커밋해시 태그를 인풋으로 배포
- 상용서버 수동배포 -> 도커허브 semver 태그를 인풋으로 배포
이제 번거롭게 ec2 접속해서 export로 변수 설정하고 docker compose up 할 필요 없습니다
-
-
> chore: 수동 배포 워크플로우 작성

- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
- close #250 
- 디코 연동 전에는 discordUsername과 nickname이 null이므로 `@NotBlank`조건을 제거했습니다.
-
-
> fix: 디스코드 연동 전에도 다른 값들을 수정할 수 있도록 DTO 변경

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
- close #262 
- `@Where`는 [deprecated](https://docs.jboss.org/hibernate/stable/orm/javadocs/org/hibernate/annotations/Where.html)네요. 대신에 `@SQLRestriction`을 사용했습니다.
-
-
> refactor: Soft Delete 쿼리 조건을 @SQLRestriction으로 대체

- build.gradle
- src/test/java/com/gdschongik/gdsc/config/TestQuerydslConfig.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
- src/test/java/com/gdschongik/gdsc/integration/DatabaseCleaner.java
- src/test/java/com/gdschongik/gdsc/integration/IntegrationTest.java
- close #267 
- 통합 테스트 템플릿 구현
- 모든 통합 테스트는 해당 `IntegrationTest` 를 상속받아서 사용합니다. 
- 데이터베이스 클리너 구현
- 테이블 데이터를 모두 truncate 한 뒤 pk 시작 순서를 다시 1부터 지정하는 유틸리티 
- 스프링 컨테이너를 다시 생성하지 않으므로 테스트 성능 개선에 도움이 됨
-
-
> test: 통합 테스트 환경 세팅

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Department.java
- close #272
- `MemberRepositoryCustomImpl` 은 인터페이스의 구현 메서드만 존재하도록 하고, 그 외 where 절 조건에 해당하는 표현식은 별도 클래스로 분리하도록 개선
- 단순 조건이 아닌 핵심 로직을 추출한 것은 제외 (ex: `replaceNullByEmptyList`)
-
-
> refactor: QueryDSL 쿼리 조건을 별도 클래스로 분리

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryOption.java
- close #271
- `MemberQueryMethod` -> `MemberQueryOption`
- `queryOption` -> `matchesQueryOption`
- `requirementVerified` -> `isGrantAvailable`
- 도메인 로직 javadoc에 `@see isGrantAvailable` 추가
-
-
> refactor: 쿼리 메서드 이름 개선 및 연관 로직 주석 추가

- src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
- close #277
- 2차 모집 기간 후 대기 페이지로 랜딩하도록 조건 추가했습니다.
-
- 다음 온보딩 때는 1차 모집 마감과 2차 모집 마감의 LandingStatus를 다른 enum 값으로 관리하는게 좋을 것 같네요.
> feat: 2차 모집 기간 마감 시 LandingStatus 조건 추가

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
- department 리팩토링 후 학과 검색어가 null일 경우 반환하는 타입이 변경되어 발생한 이슈였습니다.
-
-
> hotfix: 학과 쿼리 메서드 수정

- src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
- close #292 
- `findAllGrantable` 메서드에 대한 테스트를 아래 case에 따라 작성했습니다.
- 모든 가입조건을 충족한 경우
- 하나만을 미충족한 경우
- 디스코드만 인증되지 않은 경우
- 재학생 여부만 인증되지 않은 경우
- 회비 납부 여부만 확인되지 않은 경우
- Bevy 연동만 확인되지 않은 경우
-
- 최초에 이슈를 너무 크게 생성한 것 같아서 PR 크기를 줄이고자 이슈 크기를 줄였습니다.
> test: 가입조건에 따른 승인 가능 멤버 조회 테스트

- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
- src/main/java/com/gdschongik/gdsc/global/security/CustomUserService.java
- close #299
- `@SQLRestriction` 도입으로 querydsl 사용이 무의미해진 메서드를 쿼리 메서드로 대체했습니다.
-
-
> refactor: findNormalByOauthId 메서드를 쿼리 메서드로 대체

- src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
- close #298
- `@SQLRestriction`에 따라 `MemberStatus.NORMAL`인 회원만 조회되어야 하므로 이에 대한 테스트를 작성했습니다.
- 모든 조회 메서드에 대해 테스트를 하는 것은 비효율적이므로 `findAll` 메서드에 대해서만 테스트를 작성했습니다.
- 멤버 상태를 `MemberStatus.FORBIDDEN`으로 바꾸는 도메인 메서드가 없기 때문에 이에 대한 테스트는 작성하지 않았습니다. 향후 메서드가 구현되면 테스트를 작성하면 좋을 것 같습니다.
-
-
> test: SQLRestriction에 대한 테스트 추가

- .github/workflows/develop_build_deploy.yml
- .github/workflows/production_build_deploy.yml
- .github/workflows/pull_request_gradle_build.yml
- close #308
- [Using the action to execute Gradle via the `arguments` parameter is deprecated](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated)
- setup-gradle에서 argument로 test, build, check 등을 할 수 있었지만, v4부터는 argument가 deprecate되므로 `./gradlew build`와 같이 별도의 단계로 분리했습니다.
-  [The `build-scan-terms-of-service` input parameters have been renamed](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-build-scan-terms-of-service-input-parameters-have-been-renamed)
- setup-gradle 액션의 parameter 중 rename된 것들을 수정했습니다. 'service'가 'use'로 rename 되었습니다.
- <https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-build-scan-terms-of-service-input- …
> chore: setup-gradle 업그레이드 대응

- .github/workflows/develop_build_deploy.yml
- .github/workflows/production_build_deploy.yml
- close #311
- build-scan-report가 생성은 되는데 슬랙으로 전송되지 않는 문제였습니다.
- Issue #308 에서 빌드를 Setup 단계와 분리했으므로 build-scan-report도 분리된 빌드 단계에서 생성됩니다. 이에 따라 `id: gradle`을 `Build with Gradle` 단계로 옮겼습니다.
-
-
> chore: id를 빌드 단계로 이동

- src/main/java/com/gdschongik/gdsc/domain/common/model/BaseTimeEntity.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DiscordEventHandler.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/JoinCommandHandler.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/MemberGrantEventHandler.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/SpringEventHandler.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/JoinCommandListener.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/MemberGrantEventListener.java
- src/main/java/com/gdschongik/gdsc/domain/discord/exception/DiscordEventHandlerAspect.java
- src/main/java/com/gdschongik/gdsc/domain/discord/exception/SpringEventHandlerAspect.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberGrantEvent.java
- src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/property/DiscordProperty.java
- src/main/java/com/gdschongik/gdsc/global/util/DiscordUtil.java
- src/main/resources/application-discord.yml
- close #303
(분량 조절에 실패했습니다 죄송합니다 흑흑ㅠ)
- 이번 작업의 핵심은 유저가 직접 `/가입하기` 명령어를 입력하는 대신, 어드민에서 승인하면 자동으로 디스코드 역할을 부여하게 만드는 것입니다.
- `어드민에서 가입승인하기` 와 `디스코드에서 역할부여하기` 라는 두 로직이 하나의 서비스 메서드에 위치하게 되는 경우, 아래와 같은 문제가 있습니다.
1) 서로 관련없는 서비스 간 결합도가 증가합니다.
2) 디스코드에서 예외가 발생했을 때 트랜잭션이 롤백되어 가입승인이 취소되는 문제가 발생합니다.
- 이를 해결하기 위해 '멤버 가입승인 이벤트'를 발행하고 -> 이벤트 리스너에서 디스코드 역할부여를 수행하는 식으로 두 로직이 느슨하게 결합될 수 있도록 만들었습니다.
- 먼저 Spring Data JPA에서 제공하는`AbstractAggregateRoot` 를 사용하여 멤버 가입승인 이벤트를 발행하도록 했습니다.
- ApplicationEventPublisher를 사용하여 서비스 레이어에서 이벤트를 발행해도 되지만, 멤버 도메인 객체가 승인될 때 승인 이벤트에 대한 발행 책임까지 가지는 편이 도메인 일관성 측면에서 적합하다 판단했습니다.
- 단 AbstractAggregateRoot에서 등록한 이벤트를 처리하기 위해서는 명시적으로 `repository.save()` 를 호출해줘야 합니다.
---
- 디스코드 패키지의 이벤트 리스너 - 핸들러 구조는 JDA 이벤트에 한정되어 있었고, 때문에 JDA의 `GenericEvent` 를 인자로 받고 있었습니다.
- 하지만 이번 요구사항으로 스프링 이벤트 …
> feat: 가입 승인 시 자동으로 디스코드 역할을 부여하도록 변경

- src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
- close #310 
- MemberRole에 대한 레포지토리 테스트를 작성했습니다.
- 승인 전과 후의 상황에 대해서, GUEST와 USER로 조회하는 상황을 테스트합니다.
```java
private static final String UNIV_EMAIL = "test@g.hongik.ac.kr";
private static final String DISCORD_USERNAME = "testDiscord";
private static final String NICKNAME = "testNickname";
private static final String NAME = "김홍익";
private static final String STUDENT_ID = "C123456";
private static final String PHONE_NUMBER = "01012345678";
```
- 멤버 토메인 테스트에서도 사용하는 상수들을 레포지토리 테스트에서도 똑같이 사용해야 합니다.
각 테스트에서 상수를 정의하기 보다는 상수 클래스를 활용하는 것이 좋을 것 같아, 
Issue #313 을 열었습니다.
-
> test: MemberRole에 대한 멤버 레포지토리 테스트

- src/main/java/com/gdschongik/gdsc/domain/application/application/ApplicationService.java
- src/main/java/com/gdschongik/gdsc/domain/application/dao/ApplicationRepository.java
- src/main/java/com/gdschongik/gdsc/domain/application/domain/Application.java
- src/main/java/com/gdschongik/gdsc/domain/common/model/BaseTermEntity.java
- src/main/java/com/gdschongik/gdsc/domain/common/model/Semester.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/resources/application-test.yml
- close #319
- application 엔티티, 서비스, 레포지토리를 생성했습니다.
- 활동 기간을 나타내는 BaseTermEntity를  MappedSuperClass로 만들고 Application이 이를 상속하도록 했습니다.
- BaseTermEntity의 Semester는 Enum 타입으로 만들어 넣었습니다.
- 테스트가 깨져서 원인을 파악해보니 h2에서 year가 예약이기 때문이었고, `application-test.yml`에서 year를 사용할 수 있도록 설정했습니다.
-
- service가 담기는 application 패키지와 이름이 같은게 좀 걸리네요.. 여전히 Application을 대체할 이름이 떠오르질 않는데 좋은 이름 생각나는게 있으신 분은 comment 남겨주세요!
> feat: application 도메인 구현

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/BasicMemberInfoRequest.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberRegisterRequest.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- close #339 
- 원래는 payment까지 없애려고 했는데 연결된 부분들이 많아서 grant()시 USER -> ASSOCIATE로 변경하는 부분만 바꾸고 테스트 코드도 변경하였습니당~
- 자세한 변경 사항
- 가입 신청 -> register함수
- 회원가입 signUp함수 (기존의 signup이 존재해서 singUp으로 명칭 정함)
- 기존의 재학생 인증, 디스코드 인증, Bevy인증 에 isSignUpAvailable 인증 로직 추가해서 변겅
- isSignUpAvailable은 boolean 리턴하고 기존의 isGrantAvailable과 비슷한 로직임. 이 boolean 함수를 사용한 이유는 인증할 때마다 signUp가능한지 validate함수를 바로 해버리면 예외처리를 해버리니, 일단 조건을 만족했다상태는 것은 저장이 되어야 하므로 boolean 리턴하게 함
- signUp(회원가입할 때) validateSignupAvailable을 따로 구현하여 exception 발생 시 예외처리 할 수 있게끔 구현하였습니다. 
-  !!정책 요구사항 관련!! 가입 신청(용어는 생각해보겠습니다..) , grant -> sign up (로직 변경)
- 이벤트 처리는 이슈 새로 파서 처리를 할 예정입니다.
- To do 코드 추가 : 디스코드 기능 중에 USER 쓰는 부분있어서 맨 마지막에 한꺼번에 수정 할때 USER 삭제하기
> refactor: 멤버 엔티티 승인 함수 준회원 승급으로 변경

- src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
- src/main/java/com/gdschongik/gdsc/global/common/constant/TemporalConstant.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
- close #333
- ~~`academicYear`와 `semesterType`을 dto로 받을지 고민이었는데 일단은 모집기간 시작일을 기준으로 서버에서 처리하도록 구현했습니다.~~
- ~~dto로 입력 받는다면 모집기간 시작일과 어긋나지 않는지 (예를 들어, 모집 기간 시작일은 24년 2월인데 `academicYear`와 `semesterType`을 2023, `SECOND`로 입력한 경우) 검증이 필요해지므로,
서버에서 직접 처리하는게 좋다고 판단했습니다.~~
- ~~semesterType은 시작일의 Month를 기준으로 1 ~ 6월은 `FIRST`, 7 ~ 12월은 `SECOND`가 되도록 했습니다.~~
- 검증해야 할 사항은 아래와 같습니다. 
1. 기간이_중복되는_Recruitment가_있다면_실패한다
2. 신청 시작일과 종료일은 모두 미래의 시점이다.
3. 신청 시작일과 종료일의 year가 dto의 academicYear와 일치하는가
4. 신청 시작일과 종료일의 학기가 dto의 semesterType과 일치하는가
5. 신청 시작일과 종료일이 학기 시작일(3/1 혹은 9/1)로부터 2주 이내에 있는가
ii의 경우 dto에서 어노테이션으로 검증되는 부분이라 test를 작성하지는 않았습니다.
- 1차 모집 기간의 직전일에 기존 REGULAR 회원들을 모두 ASSOCIATE로 강등시키는 로직이 빠져있습니다.
이 부분은 코드 몇 줄로 끝나지 않을 것 같고 별도 이슈로 만들어 처리하는게 pr 리뷰하시기에 편할 것 같아서 todo 주석만 남겨뒀습니다.
-
> feat: Recruitment 생성 API 구현

- .gitignore
- src/main/java/com/gdschongik/gdsc/domain/common/vo/Money.java
- src/main/java/com/gdschongik/gdsc/domain/coupon/domain/Coupon.java
- src/main/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCoupon.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/java/com/gdschongik/gdsc/domain/coupon/domain/CouponTest.java
- src/test/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCouponTest.java
- src/test/java/com/gdschongik/gdsc/global/common/constant/CouponConstant.java
- close #342
- 쿠폰 도메인을 구현했습니다.
- 쿠폰 도메인은 쿠폰 엔티티와 발급쿠폰 엔티티로 구성됩니다.
- 쿠폰 기능의 경우 어드민이 쿠폰을 생성하고 -> 생성된 쿠폰을 멤버에게 발급하는 절차로 진행됩니다.
- 즉 쿠폰의 경우 할인금액 등 쿠폰에 대한 정보를, 발급쿠폰의 경우 발급대상 및 사용여부 등 쿠폰 히스토리에 대한 정보를 관리합니다.
- 발급쿠폰의 경우 사용여부가 존재하는데, 이는 내부적으로 필드를 두지 않고, 대신 사용일시의 존재여부로 판단합니다. (테스트 코드 참고)
- 발급쿠폰 엔티티에서는 다음 행위가 가능합니다.
- 발급쿠폰 사용하기
- 이미 사용하거나, 회수된 쿠폰인 경우 사용 불가
- 발급쿠폰 회수하기
- 이미 사용한 쿠폰인 경우 회수 불가
- 그리고 도메인 로직의 경우, 굳이 메서드 이름에 도메인 이름을 중복시킬 필요가 없다고 판단하여 제외했습니다.
- 즉 `coupon.useCoupon` 대신 `coupon.use` 가 더 적절하다 생각하여 변경했습니다. 
- 마찬가지로 정적 팩토리 생성자도 `IssueCoupon.issue` 로 변경했습니다.
- 에러코드 컨벤션이 조금 다른데요, 같은 상태로 인해 발생하는 예외더라도 사용 상황이 다르면 다른 에러코드로 출력하기 위해 이렇게 했습니다.
- 가령 '이미 사용된 쿠폰'인 경우 '재사용 케이스'와 '회수 케이스' 라는 맥락이 다르기 때문에, 분리했습니다.
- 즉 `대상도메인_불가능한행위_불가능한이유` 와 같이 네이밍 컨벤션을 가져가려고 합니다. (ex: `COUPON_NOT_USABLE_ALREAY_USED`)   
- 금액에 …
> feat: 쿠폰 도메인 구현

- src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberBasicInfoResponse.java
- close #324
- 대시보드에서 호출할 `멤버 기본 회원정보` api를 구현했습니다.
- 단순 조회이고 특별한 요구사항이 없어서 test는 생략했습니다.
-
-
> feat: 멤버 기본 회원 정보 조회 API 구현

- src/main/java/com/gdschongik/gdsc/global/security/CustomOAuth2User.java
- src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
- close #363
- 리쿠르팅 추가되면 모집 대기 / 종료 페이지가 존재할 필요 없음 (프론트에게 공유 필요)
- 기존에는 모집기간 외 회비 납부 및 grant() 막기 위하여 별도 페이지로 랜딩시키게 하였음
- 현재는 정회원 신청 섹션이 별도로 존재하므로, 항상 대시보드로 랜딩하더라도 문제 생길 여지 없음
- 마찬가지로 회원정보 입력 페이지 랜딩도 준회원 가입조건으로 통합되었으므로, 이제부터 항상 대시보드로 랜딩해야 함
-
-
> feat: 온보딩 로그인 시 항상 대시보드로 랜딩하도록 변경

- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DiscordIdBatchCommandHandler.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberAssociateEventHandler.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/listener/MemberAssociateEventListener.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberAssociateEvent.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/MemberIntegrationTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- close #348 
- event handling 꽤 ..어렵네영ㅋ..
- 준회원 승급 조건 추가하면서 event 처리로 멤버 도메인 ASSOCIATE 승급 로직을 구현했습니다
- 일단 제가 결론 부터 말씀드리자면 Event 레코드 안에 멤버를 넣어서 전파하는 방식을 택하니까! 굳이 login안해도 테스트 다 정상적으로 작동하고  event handling에 더 적합하다 싶어서 현재 코드 방식으로 짜놓았습니다 ㅎㅎ
- 제가 저번에 integration test에 이제 준회원 승급 조건을 넣어서 로직 검증을 짜놓아야 된다고 말씀드렸는데, isAllVerified라는 중간 검증이 생겨버리니 굳이 통합 테스트에서 승급할 필요없이 isAllverified를 만족시키는지만 확인하면 돼서 Member 도메인 테스트에 수정/추가 해두었습니다!
- isAllverified라는 도메인 로직 검증 메서드가 생긴 이유는 event handler에서 코드를 개선시킬 수 있을 것 같아서 추가했습니다.. 그리고 굳이 Requirement에 isAllVerified 필드를 추가 하지 않고 그냥 메소드 호출할때 저 멤버가 현재 다 verified인지 검증만 해주면 될 것 같아서 코드를 짯습니다!
- eventListener에 대한 검증 테스트는 안했는데 적절하다고 생각하시나요? 의견 궁금하네요!
- + 짜고 보니까 isAllVerified부분 테스트 메서드 이름이 조금 어색하네영...좀만 더 생각해볼게요 저 이름은! 
- @DomainEvents라는 어노테이션을 사용해서 requirement가 디비에 수정되는 순간 원하는 이벤트 …
> refactor : 멤버 도메인 준회원 승급 조건 추가 - 기본 정보 작성

- src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Round.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RoundType.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
- src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
- close #369
- 리쿠르팅에 Money(회비)와 RoundType(차수)를 추가했습니다. RoundType은 Enum으로 관리합니다.
- `학년도, 학기, 차수가 모두 중복되는 리쿠르팅`은 생성하지 못하도록 리쿠르팅 생성 Api를 수정했습니다.
- test에서 수정된 파일이 많기는 하지만 대부분 `Recruitment.createRecruitment` 메서드 수정에 따른 변화입니다.
-
-
> feat: 리쿠르팅에 회비와 차수 추가

- src/main/java/com/gdschongik/gdsc/domain/email/dao/UnivEmailVerificationRepository.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
- close #385
- no usage인 repository 로직들을 제거했습니다.
- 가입 신청서 작성 여부를 판단하기 위해 사용하던 `isStudentIdNotNull()`는 
`eqRequirementStatus(member.associateRequirement.infoStatus, VERIFIED))`로 대체했습니다.
- #376 에서 제거 누락된 `UnivEmailVerificationRepository`를 제거했습니다.
-
> refactor: 사용하지 않는 QueryDSL 로직 제거

- src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/MemberFullDto.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberDashboardResponse.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
- src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
- src/main/java/com/gdschongik/gdsc/domain/membership/dao/MembershipRepository.java
- src/main/java/com/gdschongik/gdsc/domain/membership/dto/MembershipFullDto.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/application/OnboardingRecruitmentService.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/RecruitmentFullDto.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/main/java/com/gdschongik/gdsc/global/util/formatter/PhoneFormatter.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
- src/test/java/com/gdschongik/gdsc/integration/IntegrationTest.java
- close #362
- 여러 DTO를 aggregate 하는 응답의 경우 각 엔티티에 대응되는 DTO를 조합하여 만듭니다.
- 이때 모든 필드가 대응되는 DTO의 경우 `XXXFullDto` 로, 일부 필드만 대응되는 DTO의 경우 `XXXSimpleDto` 로 네이밍합니다.
- `SimpleDto`의 경우 리스트 반환 시 원본 엔티티의 필드가 너무 많은 경우에만 사용하며, 그 외에는 사용하지 않습니다.
- 추후 displayPeriod 등으로 리팩토링할 것으로 고려하여 현재는 `isOpen`으로 판단하게 했습니다.
- `isDisplayable` 생기면 간단하게 변경해주시면 됩니다.
- 정회원 신청을 하지 않은 유저인 경우, 현재 열려있는 리쿠르팅에 대하여 멤버십이 존재하지 않을 수 있습니다.
- 이를 위해 `OnboardingMembershipService#findMyMembership`이 Optional로 리턴하도록 했습니다.
- 그리고 DTO 변환 시 null 이면 해당 DTO 필드도 null이 되도록 만들었습니다.
- 학과명 반환 시 NPE 방지 위해 Optional로 싸놨습니다.
- 통합 테스트에 리쿠르팅 템플릿 만드는 메서드 추가했습니다.
- `isOpen`의 경우 `LocalDateTime.now()` 사용하는데 생성되는 템플릿은 과거 시점이므로 조회되지 않습니다. 이를 해결하기 위해 서비스를 모킹하여 `findCurrentRecruitment` 가 항상 템플릿 리쿠르팅을 반환하도록 만들었습니다.
- `@MockBean`의 경우 자식 테스트에 두면 해당 테스트 실행 시 컨텍스트를 …
> feat: 온보딩 대시보드 페이지 API 구현

- src/main/java/com/gdschongik/gdsc/domain/common/model/RequirementStatus.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/CommonDiscordService.java
- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DiscordIdBatchCommandHandler.java
- src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
- src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
- src/main/java/com/gdschongik/gdsc/domain/membership/domain/RegularRequirement.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- close #390
- verified를 satisfied로 rename 했습니다.
- 관련 메서드들의 이름도 모두 변경했습니다.
- ErrorCode 중, `MEMBER_ALREADY_VERIFIED`는 사용처가 없어서 수정대신 제거했습니다.
-
> rename: `VERIFIED`를 `SATISFIED`로 변경

- src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- close #410
- 대기중인 회원 조회 API와 관련 서비스 메서드를 제거했습니다.
- `AdminMemberService`에서 대기중인 회원 조회 API와는 무관하지만 사용하지 않는 `findAll` 메서드가 있어서 같이 제거했습니다.
-
> refactor: 대기중인 회원 조회 API 제거

- src/main/java/com/gdschongik/gdsc/domain/study/domain/Difficulty.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistory.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyNotification.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyType.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
- close #409
- 스터디 테이블 (Study)
- 스터디 세션 테이블(커리큘럼 + 과제) (StudyDetail)
- 수강 히스토리 테이블 (StudyHistory)
- 스터디 공지사항 테이블 (StudyNotification)
이렇게 우선적으로 추가해두겠습니다.
추가 변경 및 추가사항 생기면 각 도메인 작업할때 추가해주세요!
StudyDetail은 Session, Assignmen 두개의 Vo와 공통데이터로 나눴습니다.
-
-
> feat: 스터디 도메인 테이블 추가

- src/test/java/com/gdschongik/gdsc/domain/coupon/application/CouponServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/MemberIntegrationTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
- src/test/java/com/gdschongik/gdsc/helper/DatabaseCleaner.java
- src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
- src/test/java/com/gdschongik/gdsc/helper/RepositoryTest.java
- close #293
- `IntegrationTest`와 `RepositoryTest` 모두 `DatabaseCleaner`를 사용하지만, 
지금의 디렉토리 구조는 `DatabaseCleaner`를 `IntegrationTest`에서만 사용하던 때의 구조입니다.
현재는 `RepositoryTest`에서도 사용하므로 config, domain, global과 같은 위치에 helper 패키지를 만들고 위의 세 가지 파일을 모두 안으로 넣었습니다.
-
-
> test: 테스트 템플릿 위치 변경

- src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DelegateMemberDiscordEventHandler.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberRegularEvent.java
- src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
- src/main/java/com/gdschongik/gdsc/global/util/DiscordUtil.java
- close #332
- 디스코드 유저네임을 사용하여 Member를 찾던 `DelegateMemberDiscordEventHandler`에서 디스코드 id를 사용하도록 수정했습니다.
-
-
> refactor: 디스코드 유저네임 활용 로직을 id 활용으로 변경

- src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
- src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
- close #415 
- 추후 작업에 필요한 엔티티 안에 필드명 수정했습니다~
-
-
> refactor: 과제 엔티티 필드 이름 수정

- build.gradle
- src/main/java/com/gdschongik/gdsc/domain/coupon/domain/Coupon.java
- src/main/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCoupon.java
- src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
- src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
- src/main/java/com/gdschongik/gdsc/domain/order/api/OnboardingOrderController.java
- src/main/java/com/gdschongik/gdsc/domain/order/application/OrderService.java
- src/main/java/com/gdschongik/gdsc/domain/order/dao/OrderRepository.java
- src/main/java/com/gdschongik/gdsc/domain/order/domain/MoneyInfo.java
- src/main/java/com/gdschongik/gdsc/domain/order/domain/Order.java
- src/main/java/com/gdschongik/gdsc/domain/order/domain/OrderStatus.java
- src/main/java/com/gdschongik/gdsc/domain/order/domain/OrderValidator.java
- src/main/java/com/gdschongik/gdsc/domain/order/dto/request/OrderCreateRequest.java
- src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
- src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/order/domain/MoneyInfoTest.java
- src/test/java/com/gdschongik/gdsc/domain/order/domain/OrderValidatorTest.java
- src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
- src/test/resources/application-test.yml
- close #343
- 클라이언트는 결제를 요청하기 전에 임시 주문 생성
- 이런저런 절차 거쳐서 결제 성공하면 서버로 결제 성공 요청을 보냄
- 그러면 서버는 토스페이먼츠 서버로 결제 승인 요청을 보내고, 아까 전에 만들어둔 임시 주문을 성공 처리함
- 일단 주문에 사용되는 연관 엔티티의 ID 정보 및 금액정보만 저장 -> 추후 토스페이먼츠 측에서 전달하는 정보 저장할 예정
- 발급쿠폰의 경우 사용할 수도, 사용하지 않을 수도 있음
- 금액정보의 경우 `MoneyInfo` VO로 관리 -> `주문총액 - 쿠폰할인금액 = 최종결제금액` 불변식 지키기 위함 (테스트 참고)
- 요청으로는 1) 주문 nano id 2) 회비납입상태를 갱신하고자 하는 멤버십 id 3) (있는 경우) 사용하려는 발급쿠폰 id 4) 클라이언트에서 사용자에게 디스플레이한 금액 정보를 받는다
- 발급쿠폰 id가 요청 바디에 담겼다면 조회, 아니라면 null
- 관련 엔티티를 조회하고, VO를 생성한 다음, 도메인 서비스에 해당하는 `OrderValidator` 에게 결제 유효성 검증 요청
- 주문 검증기는 아래와 같은 도메인 규칙을 검증함
1. 멤버십의 대상 멤버가 현재 로그인한 멤버와 일치하는가?
2. 멤버십의 정회원 승급조건 중 회비납입상태를 아직 충족하지 못했는가?
3. 멤버십이 참조하는 리쿠르팅이, 현재 지원 가능한 리쿠르팅인가?
4. (발급쿠폰이 있다면) 발급쿠폰의 소유자가 현재 로그인한 멤버와 일치하는가?
5. (발급쿠폰이 있다면) 발급쿠폰이 사용 가능한가? (== 회수되지 않았고, 사용되지 않았는가?)
6. 주문총액이 …
> feat: 임시 주문 생성 API 구현

- src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
- close #675
- api서버 주소가 없어서 스웨거 cors난거같네요
-
-
> fix: dev 스웨거 cors에러 해결

- src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentResponse.java
> fix: AssignmentResponse 잘못된 값 매핑 수정

- src/main/java/com/gdschongik/gdsc/domain/studyv2/api/StudentStudyHistoryControllerV2.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/application/StudentStudyHistoryServiceV2.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dao/StudyAchievementV2Repository.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dao/StudyHistoryV2Repository.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dto/dto/StudyAchievementDto.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dto/dto/StudyHistoryDto.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dto/dto/StudyStudentDto.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dto/response/StudyHistoryMyResponse.java
- close #914
- 기존 V1 API의 경우 '수료내역' 조회로 되어있고 메서드명도 `geMyCompletedStudyHistories` 로 되어있는데요, 실제 피그마 디자인을 보면 전체 수강이력을 가져와야 하고, 실제 조회 로직도 status가 COMPLETED된 것만 필터링하는 로직이 없습니다.
- 따라서 수료내역이 아닌 '수강이력 목록' 조회로 네이밍을 변경하고 관련 DTO도 네이밍 맞춰주었습니다.
++ DTO 사용하는 방식 한번씩 체크해주세요. 앞으로 DTO 코딩 컨벤션은 이렇게 진행할 예정입니다
대시보드 API나 수강이력 API처럼, 다른 엔티티를 같이 묶어서 반환하는 API의 경우,
모든 필드를 flatten하여 처리하지 않고, 각 엔티티와 1대1 대응되는 DTO를 조합하여 리턴합니다. (StudyHistoryMyResponse = StudyStudentDto + StudyHistoryDto + StudyAchievementDto)
-
-
> feat: 내 스터디 수강이력 목록 조회 V2 API 구현

- src/main/java/com/gdschongik/gdsc/domain/studyv2/application/StudentStudyServiceV2.java
- src/main/java/com/gdschongik/gdsc/domain/studyv2/dto/response/StudyDashboardResponse.java
- close #917 
- 기존에는 '나의 과제' 탭에서 레포지토리 링크 입력과 제출 가능한 과제 리스트를 조회했다면, 해당 기능이 커리큘럼 탭으로 넘어오면서 굳이 별도 api 로 분리할 필요가 없을 것 같다고 생각해서 기존 대시보드 조회 api 에서 `study history` 정보를 함께 조회하도록 추가했습니다.
- 
- 기존의 StudyHistoryDto 에서 레포지토리 링크 필드가 'githubLink' 로 되어있는데, 필드명을 'repositoryLink' 로 수정하면 더 직관적일 것 같다고 생각하는데, 혹시 어떻게 생각하시나요?
- 기능 구현하면서 궁금한 점이 있는데, 지금과 같이 '레포지토리 링크' 필드 하나가 필요한 상황에서 StudyHistoryDto 전체를 필드로 받으면 실제로 응답에 필요하지 않은 필드들도 다수 응답하게 되는데, 이런 경우에도 Dto를 사용하여 응답하면 될까요? @uwoobeat
> feat: 대시보드 조회 응답에 레포지토리 링크 추가

- src/main/java/com/gdschongik/gdsc/global/config/ObjectMapperConfig.java
- close #981
- `ObjectMapperConfig` 말고는 외부에서 사용 안 하길래 public 제거했습니다.
-
-
> refactor: 직렬화 및 역직렬화기 inner class를 static으로 변경

- src/main/java/com/gdschongik/gdsc/domain/studyv2/dto/response/StudyDashboardResponse.java
- close #994
- 스터디 대시보드 조회시에도 #988 과 비슷한 이유로 NPE 가 발생하여 null 체크 로직 추가했습니다
-
-
> fix: 스터디 대시보드 조회시 커밋 시점이 null 인 경우 NPE 발생

- src/main/java/com/gdschongik/gdsc/domain/member/api/TestMemberController.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberTokenByOauthIdRequest.java
- close #1036
- #1032 
- 해당 이슈에서 이야기한 내용 적용해 oauthId 를 이용해서 테스트용 토큰을 발급받는 기존 API 제거
-
-
> refactor: `oauthId` 기반 테스트용 로그인 API 제거

- src/main/java/com/gdschongik/gdsc/infra/github/client/GithubClient.java
- close #1034
https://github.com/GDSC-Hongik/gdsc-server/pull/1032#discussion_r2032931097
해당 제안 반영해 변경
- `GithubClient` 가 API와 통신 전 항상 `new ObjectMapper()` 를 생성해서 사용하고 있던 상황 
- `GithubClient` 생성시에 ObjectMapper 주입 받도록 변경
-
-
> refactor: `GithubClient` Object Mapper 주입받도록 변경

- src/main/java/com/gdschongik/gdsc/domain/common/model/BaseSemesterEntity.java
- src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
- src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/order/dao/OrderCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/order/dao/OrderQueryMethod.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRoundCustomRepository.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRoundCustomRepositoryImpl.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRoundRepository.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRound.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentResponse.java
- src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentRoundResponse.java
- src/main/java/com/gdschongik/gdsc/global/util/formatter/SemesterFormatter.java
- src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberValidatorTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
- src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidatorTest.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidatorTest.java
- src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
- src/test/java/com/gdschongik/gdsc/global/common/constant/TemporalConstant.java
- src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
- src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
- close #956
- close #803 
- close #774
- 기존 리팩토링 의도는 Semester 내부에 semester period 까지 담아서 관리하고 싶었는데, 외부에서 Semester 를 다룰 때 (연도, 학기) 조합으로 다루는 경우가 많다보니 구체적인 period 까지 담으면 오히려 불편할 것 같았습니다.
- 그래서 period 는 기존 처럼 recruitment 엔티티가 갖고 있는 대신, 이전 이슈로도 있었던 recruitment round 에서 semester 를 없애는 리팩토링을 진행하였습니다.
-
-
> refactor: Recruitment 엔티티에 Semester 필드 추가
